# Generated by Django 4.0.4 on 2022-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_boost_level_alter_core_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
