# Generated by Django 4.0.4 on 2022-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_added_boost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='auto_click_power',
            field=models.IntegerField(default=1),
        ),
    ]
